# 我的伊甸园 - 应用配置文件
# 包含数据库、Redis、JWT、文件上传等配置

server:
  port: 38080
  servlet:
    context-path: /api

spring:
  application:
    name: my-eden-backend
  
  # MongoDB配置
  data:
    mongodb:
      host: localhost
      port: 27017
      database: myeden
      username: myeden
      password: password!
      authentication-database: myeden
      auto-index-creation: true

    redis:
      host: 192.168.1.190
      port: 6379
      password: 
      database: 0
      timeout: 2000ms
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0
          max-wait: -1ms
  
  # 文件上传配置
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
      enabled: true
  
  # Jackson配置
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    default-property-inclusion: non_null
    serialization:
      write-dates-as-timestamps: false
      fail-on-empty-beans: false
    deserialization:
      fail-on-unknown-properties: false
  
  # 配置文件加载
  config:
    import:
      - optional:file:../config/world-config.yaml
      - optional:file:../config/robots-config.yaml

# JWT配置
jwt:
  secret: myeden-secret-key-2025-very-long-and-secure
  expiration: 86400000  # 24小时
  refresh-expiration: 604800000  # 7天
  issuer: myeden
  audience: myeden-users

# 文件存储配置
file:
  upload:
    path: ./uploads
    allowed-types: jpg,jpeg,png,gif
    max-size: 5242880  # 5MB

# Dify API配置
dify:
  api:
    url: http://rag.kingfisher.live/v1
    key: app-ubH4cOXoYkDZDzr96AHl1OHU
    timeout: 30000  # 30秒
    max-retries: 3
    retry-interval: 1000  # 1秒
    enabled: true
    daily-limit: 1000
    retry:
      max-attempts: 3
      delay: 1000  # 1秒

# 机器人行为配置
robot:
  behavior:
    enabled: true
    check-interval: 60000  # 1分钟检查一次
    max-concurrent-actions: 5
    cooldown-period: 300000  # 5分钟冷却期

# 日志配置
logging:
  level:
    com.myeden: DEBUG
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG
    org.springframework.data.mongodb: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: logs/myeden.log
  logback:
    rollingpolicy:
      max-file-size: 10MB
      max-history: 30

# 管理端点配置
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always
  prometheus:
    metrics:
      export:
        enabled: true

# 跨域配置
cors:
  allowed-origins: 
    - http://localhost:3000
    - http://localhost:5173
    - http://127.0.0.1:3000
    - http://127.0.0.1:5173
  allowed-methods: GET,POST,PUT,DELETE,OPTIONS
  allowed-headers: "*"
  allow-credentials: true
  max-age: 3600 