# 我的伊甸园 - 应用配置文件
# 包含数据库、JWT、文件上传等配置

server:
  port: 38080
  servlet:
    context-path: /

spring:
  application:
    name: my-eden-backend
  
  # MongoDB配置 - 性能优化版本
  data:
    mongodb:
      host: localhost
      port: 27017
      database: myeden
      username: myeden
      password: password!
      authentication-database: myeden
      auto-index-creation: true
      # 连接池配置
      connection-pool:
        max-size: 100
        min-size: 5
        max-wait-time: 30000
        max-connection-life-time: 300000
        max-connection-idle-time: 60000
      # 查询优化配置
      read-preference: primary
      write-concern: majority
      read-concern: majority
      # 索引优化
      index-creation: true
      # 查询超时配置
      socket-timeout: 30000
      connect-timeout: 10000
      server-selection-timeout: 30000
      # 批量操作优化
      batch-size: 1000
      # 聚合管道优化
      aggregation-options:
        allow-disk-use: true
        max-time: 30000

  # 文件上传配置
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB
      enabled: true
  
  # Jackson配置
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    default-property-inclusion: non_null
    serialization:
      write-dates-as-timestamps: false
      fail-on-empty-beans: false
    deserialization:
      fail-on-unknown-properties: false
    # 添加LocalDate格式化配置
    format:
      date: yyyy-MM-dd
      date-time: yyyy-MM-dd HH:mm:ss
  
  # 配置文件加载
  config:
    import:
      - optional:file:../config/world-config.yaml
      - optional:file:../config/robots-config.yaml

# JWT配置
jwt:
  secret: myeden-secret-key-2025-very-long-and-secure
  expiration: 86400000  # 24小时
  refresh-expiration: 604800000  # 7天
  issuer: myeden
  audience: myeden-users

# 文件存储配置
file:
  upload:
    path: ./uploads
    allowed-types: jpg,jpeg,png,gif,webp
    max-size: 5242880  # 5MB

# WebSocket配置
websocket:
  endpoint: /ws
  allowed-origin-patterns: "*"
  heartbeat:
    interval: 30000  # 30秒心跳间隔
    timeout: 60000   # 60秒超时
  message:
    deduplication-window: 5000  # 5秒去重窗口
    max-history: 1000  # 最大消息历史
  connection:
    max-sessions-per-user: 3  # 每个用户最大会话数
    session-timeout: 3600000  # 1小时会话超时

# Dify API配置
dify:
  api:
    url: http://rag.kingfisher.live/v1
    key: app-ubH4cOXoYkDZDzr96AHl1OHU
    timeout: 30000  # 30秒
    max-retries: 3
    retry-interval: 1000  # 1秒
    enabled: true
    daily-limit: 1000
    retry:
      max-attempts: 3
      delay: 1000  # 1秒
  image:
    apiKey: app-jey4nbiLS9jyiUDWeIQTcvZ5

# 机器人行为配置
robot:
  behavior:
    enabled: true
    check-interval: 60000  # 1分钟检查一次
    max-concurrent-actions: 5
    cooldown-period: 300000  # 5分钟冷却期

# 日志配置
logging:
  level:
    com.myeden: INFO
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG
    org.springframework.data.mongodb: DEBUG
    org.springframework.web.socket: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: logs/myeden.log
  logback:
    rollingpolicy:
      max-file-size: 10MB
      max-history: 30

# 管理端点配置
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always
  prometheus:
    metrics:
      export:
        enabled: true

# 跨域配置
cors:
  allowed-origin-patterns: "*"
  allowed-methods: GET,POST,PUT,DELETE,OPTIONS
  allowed-headers: "*"
  allow-credentials: true
  max-age: 3600

springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
    doc-expansion: none
    disable-swagger-default-url: true
    display-request-duration: true
  default-produces-media-type: application/json
  default-consumes-media-type: application/json 