package com.myeden.task;

import com.myeden.service.RobotDailyPlanService;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.scheduling.annotation.Scheduled;
import org.springframework.stereotype.Component;

import java.time.LocalDate;

/**
 * 机器人每日计划批量生成定时任务
 * 每天凌晨自动为所有机器人生成当天计划
 */
@Component
public class RobotDailyPlanBatchTask {

    @Autowired
    private RobotDailyPlanService planService;

    /**
     * 每天凌晨1:00自动批量生成
     */
    @Scheduled(cron = "0 0 1 * * ?")
    public void autoGenerateDailyPlans() {
        LocalDate today = LocalDate.now();
        planService.batchGenerateAllRobotsPlanByAI(today);
        // 可加日志
    }
} 